### ISSUE TITLE
Dutch POS tagging

### ISSUE THREAD

**Issue by hugobuddel** [wooorm/parse-dutch#1]
It would be interesting to me to use your [retext-pos module](https://github.com/wooorm/retext-pos) with Dutch text. Is this already possible? Or if not, could you comment on the feasibility of the following plan to achieve it?

Language processing is new to me, but after some research it seemed that you already did much of the hard work. Am I correct that there are three requirements to use retext-pos with Dutch text?:
* This module, parse-dutch,
* a Dutch version of the tagging rules of [dariusk/pos-js](https://github.com/dariusk/pos-js) and
* a Dutch lexicon.

For the lexicon it seems that the [Open Source Dutch WordNet](http://wordpress.let.vupr.nl/odwn/data/) would be able to provide most of the necessary information. A Dutch version of the tagger might not be that difficult with this parser available, because the rules of Dutch and English are not that different. At least, according to my perhaps naive perspective.

Would it be feasible to achieve Dutch pos tagging through this route? I'm willing to give it a try for my pet project. It would already be sufficient for me if the system would be capable of tagging on the 'Jip and Janneke' level.

**Comment by wooorm** [comment]
Right, I think this would be very possible. If a Dutch version of **pos-js** is available (a list of words with tags, and a basic system with some rules), I could (easily) create a Dutch version of retext-pos. As you can see from **retext-pos**’s [source](https://github.com/wooorm/retext-pos/blob/master/index.js), it’s not that much of code! Additionally, **parse-dutch** would not need to change!

I’m gonna close this issue here: It’s not really related to **parse-dutch**, let me know if I can assist in any way: e-mail is fine, or create a new project (**retext-pos-nl**?), and post an issue there where we can discuss further! :smile:

**Comment by hugobuddel** [comment]
Thank you for your swift response wooorm! I'll create a new project and keep you informed whether anything comes out of it. The reason for raising it as an issue here was twofold: one to keep the idea out of email 'vaults' and two because having a good parser is a prerequisite for a good tagger, so they are somewhat related.

**Comment by wooorm** [comment]
Sure, no problem! If you’d like, you could also re-open this issue, or just keep commenting, but I think the parser is good enough for the Dutch POS tagger! :smile: Let me know how things go!
